version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build
    overwrite: yes
file_exists_behavior: overwrite

permissions:
  - object: /
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: ./scripts/before-install.sh
      timeout: 30
      runas: ubuntu
  AfterInstall:
    - location: ./scripts/after-deploy.sh
      timeout: 30
      runas: ubuntu