version: 0.0
os: linux
files:
  - source: /appspec-auth.yml
    destination: /home/ubuntu/build/appspec.yml
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: ./scripts/after-deploy-auth.sh
      timeout: 30
      runas: ubuntu