name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install CPPUnit library
        run: sudo apt install -y libcppunit-dev

      - name: Configure project (if applicable)
        run: ./configure  # 해당 명령어가 필요하면 주석 해제

      - name: Build project
        run: make

      - name: Run unit tests
        run: make test